services:
  backend_app:
    build: 
      context: ./backend
    container_name: backend
    hostname: backend
    ports:
      - "9000:9000"


  frontend_app:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
